<?php

namespace Uevf\UserBundle\Repository;

/**
 * AccountImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountImageRepository extends \Doctrine\ORM\EntityRepository
{
}
