<?php

namespace Uevf\AdvertBundle\Repository;

/**
 * advertThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertThemeRepository extends \Doctrine\ORM\EntityRepository
{
}
