<?php

namespace Uevf\AdvertBundle\Repository;

/**
 * AdvertImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertImageRepository extends \Doctrine\ORM\EntityRepository
{
}
