<?php

namespace Uevf\PlatformBundle\Repository;

/**
 * CityFrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityFrRepository extends \Doctrine\ORM\EntityRepository
{
    
}
